### ISSUE TITLE
SNMP container to measure network parameters (BW, PL, RTT)

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-communications-pilot#25]
SNMP container returning the BW, PL and RTT of the system. Need to have an SNMP proxy since VNFs can be scaled up or in. This proxy will expose the values of the different instances.

**Comment by antonroman** [comment]
This service needs to be executed  in the VNF-RP as it will have access to all the VNF-WAC and VNF-MS available. 
The BW used by the VNF-MS will be measured using SNMP by polling the values  every 3 minutes (check variable .1.3.6.1.2.1.2.2.1.11 (outbound octets) of media interface of the VNF-MS).
The PL and Jitter (not RTT) will be provided by Janus API.

**Comment by antonroman** [comment]
The monitoring app to be deployed in the VNF-RP is going to be developed in Python using EasySNMP library (https://easysnmp.readthedocs.io/en/latest/).

**Comment by antonroman** [comment]
This is the Python line to create the connection against the VNF-instance
session = easysnmp.Session(hostname='<VNF IP>',version=3,security_level='auth_with_privacy',auth_protocol='SHA',security_username='<user>',privacy_protocol='AES',auth_password='<pass>',privacy_password='<pass>')
