### ISSUE TITLE
Error while deploying communication pilot network service

### ISSUE THREAD

**Issue by efotopoulou** [sonata-nfv/tng-communications-pilot#49]
Having some difficulties with deploying the communication pilot network service.
Problem seems be reported by the specificmanagerregistry docker container with main log:
`Instantiation failed:SSM name sonssmcommunication-pilotconfig not found!`

Attached you may find relevant logs.
@anapolg @tsoenen any idea how can be fixed this?

[specificmanagerregistry.txt](https://github.com/sonata-nfv/tng-communications-pilot/files/2970937/specificmanagerregistry.txt)
[servicelifecyclemanagement.txt](https://github.com/sonata-nfv/tng-communications-pilot/files/2970939/servicelifecyclemanagement.txt)
[functionlifecyclemanagement.txt](https://github.com/sonata-nfv/tng-communications-pilot/files/2970940/functionlifecyclemanagement.txt)
[son-sp-infrabstract.txt](https://github.com/sonata-nfv/tng-communications-pilot/files/2970943/son-sp-infrabstract.txt)

**Comment by anapolg** [comment]
After talking with @efotopoulou it seems that she's able to manually pull the image from the platform without problems but somehow, the problem seems to be:

```
sonssmcommunication-pilotconfig registration failed, Error: 'specific_manager_type'
Instantiation failed for: sonssmcommunication-pilotconfig, Registration failed- timeout error
Instantiation failed:SSM name sonssmcommunication-pilotconfig not found!
```

@tsoenen any idea?

**Comment by tsoenen** [comment]
What version of the SP are you using? communications pilot ssms and fsms 
make use of functionality that was added in november, so it can't work 
with v4.0.

**Comment by efotopoulou** [comment]
@tsoenen i am using latest stable release
guess i have no other option than switching at the latest...
When do we plan to make a new stable release?
i close the issue since it refers to v4.0 
Thank you both for your support!

**Comment by tsoenen** [comment]
You could switch to :qual, it should be fairly stable and is updated 
every Friday.

**Comment by efotopoulou** [comment]
wish i could work on :qual
Tried to deploy the communication pilot package an  our ago there and got this:
![compilotatquabcn](https://user-images.githubusercontent.com/1914256/54433532-bf9b2c80-4734-**11e9-8e8b-f16fced07e0d.png)

graylogs for source:qual-sp-bcn  and containers for servicelifecyclemanagement,son-sp-infrabstract, functionlifecyclemanagement show nothing. message at the bottom of the screen was generated pretty quickly.

**Comment by tsoenen** [comment]
You could try to restart qual, so you have a fresh instantiation?

**Comment by anapolg** [comment]
If the message was shown like that is that the request from the Portal had an error. Not because of the instantiation process. Could you please check if there is any new request after that?

**Comment by efotopoulou** [comment]
@tsoenen, which environment should i rebuild from [here](https://jenkins.sonata-nfv.eu/view/ENVIRONMENTS/) ??

@anapolg, i see no new request [here](https://qual-sp-bcn.5gtango.eu/service-management/requests) 
i just get the error message. Can you try it also? I tried to deploy the quobis communication pilot package that already exists at qual environment.
You can also find several netrwork instances deployed that are not stopped [here](https://qual-sp-bcn.5gtango.eu/service-management/network-service-instances) (maybe they should also stopped -if not needed- since they consume resources)

**Comment by tsoenen** [comment]
qual-sp-bcn, with clean set to `no`

**Comment by efotopoulou** [comment]
@tsoenen  i do not get it!
i see no `qual-sp-bcn` environment. do you mean `environment-promote-qual` ?
![environment](https://user-images.githubusercontent.com/1914256/54436328-fbd18b80-473a-11e9-9fa4-72fe823b07e8.png)
where i should declare the `no` option ?

**Comment by anapolg** [comment]
The instances can not be stopped since some attributes changed its name. Then, when Portal tries to get them to send the request to "stop the instance" it gets a failure. I'm still updating Portal to all new content these days. So for the moment you'll have to go into Openstack and remove the stack manually to avoid resources consumption.

I'm going to test right now an instantiation to see what happens but I guess it is something similar.

**Comment by tsoenen** [comment]
In this job: 
https://jenkins.sonata-nfv.eu/view/ENVIRONMENTS/job/environment-deployments/build?delay=0sec

you can select the qual-bcn-sp environment to restart.

**Comment by efotopoulou** [comment]
@tsoenen Thanks a lot !
I did not remember at all how to do this. 
restart of qual enviroment failed:
```
16:25:35 fatal: [qual-sp-bcn.5gtango.eu]: FAILED! => {"changed": false, "module_stderr": "Shared connection to qual-sp-bcn.5gtango.eu closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_fQQGZT/ansible_module_docker_container.py\", line 679, in <module>\r\n    from ansible.module_utils.docker_common import HAS_DOCKER_PY_2, AnsibleDockerClient, DockerBaseClass\r\n  File \"/tmp/ansible_fQQGZT/ansible_modlib.zip/ansible/module_utils/docker_common.py\", line 35, in <module>\r\n  File \"/usr/local/lib/python2.7/dist-packages/requests/__init__.py\", line 84, in <module>\r\n    from urllib3.contrib import pyopenssl\r\n  File \"/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py\", line 46, in <module>\r\n    import OpenSSL.SSL\r\n  File \"/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py\", line 8, in <module>\r\n    from OpenSSL import rand, crypto, SSL\r\n  File \"/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py\", line 118, in <module>\r\n    SSL_ST_INIT = _lib.SSL_ST_INIT\r\nAttributeError: 'module' object has no attribute 'SSL_ST_INIT'\r\n", "msg": "MODULE FAILURE", "rc": 0}
16:25:35 	to retry, use: --limit @/var/lib/jenkins/workspace/environment-deployments/roles/sp.retry
```
as seen [here](https://jenkins.sonata-nfv.eu/view/ENVIRONMENTS/job/environment-deployments/1036/console)

Furthermore i am not sure if restarting the environment also updates the containers. Seems that some bug fixes where realized this week and maybe this will make the qual environment operative (meaning it will be possible to deploy a network service)

Is it easy to update the qual environment with latest code?

**Comment by tsoenen** [comment]
You can use the promote-to-qual job to make latest code available in qual.

Give it another go, if it fails again, best to ask Felipe:D

**Comment by efotopoulou** [comment]
Latest code did NOT the trick! 
i will try to follow the issue via gitter!
Many thanks both of you for you support and have a nice weekend!

**Comment by anapolg** [comment]
Instantiation seems to be working in pre-int... If it helps
