### ISSUE TITLE
Create VnV-test-Com-P1a (RTT from WebRTC app to VNF)

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-communications-pilot#68]
This tests checks the RTT of packets sent from the WebRTC application to the
VNF.
● The traffic of the call needs to access through the ingress
● Quobis needs to generate the call from a head-less browser in a container
(experimental approach).
● VnV-test-Com-P1b can be used as a backup in case there is any technical
stopper.

**Comment by antonroman** [comment]
This issue depends on issue #66

**Comment by DanielVilaFalcon** [comment]
I must be done at the application level. We have tried to get RTC statistics from the WebRTC-internal when a WebRTC call would be established in the VnV, but the WebRTC-internals tool is not reachable with the headless browser.
We need study other posibilities to get the RTT of the traffic genated from a WebRTC application.

**Comment by DanielVilaFalcon** [comment]
Finally, the RTT is obtained from the Chrome tool chrome://webrtc-internal once the service is deployed and the vidio-conference is established. The result shows a RTT of 0.292 ms.

![image](https://user-images.githubusercontent.com/46524505/69130011-06a1a480-0ab0-11ea-9226-a82f4d14ab27.png)
