### ISSUE TITLE
Create VnV-test-Com-P1b test (RTT from generic app)

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-communications-pilot#69]
This tests checks the RTT of an UDP packet sent sent to the VNF-MS VNF from a
generic application.
● The traffic of the call needs to access through the ingress
● iperf can be used for this

**Comment by DanielVilaFalcon** [comment]
It is done. A container runs a ping command and we will be able to get the RTT in the VnV platform.

**Comment by DanielVilaFalcon** [comment]
Once the problems with the VnV were fixed, the test has been completed successfully.
The process to do the test is the following:
    - Create the .tgo files of the Network Service Package and Test Package
         `tng-pkg -p project.yml_path`
       Both files used to create this test are in the following links:

- Network Service Package: https://github.com/sonata-nfv/tng-communications-pilot

- Test Package: https://github.com/DanielVilaFalcon/tng-tests/tree/headless-browser/packages/TEST_COMM_RTT

-Upload both .tgo files to the VnV platform. It can be done from command line interface:
`	tng-cli -u http://pre-int-vnv-bcn.5gtango.eu package -u <path .tgo>`

Once both packages are uploaded, and if the testing tag flags of the project.yml match each other, the platform deploys the service in the qual-sp and executes the test.
It shows as result the content of the result.log file locate in /output/${PROBE}/$HOSTNAME/results.log

![imagen](https://user-images.githubusercontent.com/46524505/63420981-16a1dd80-c408-11e9-97d8-b3ae592a3e81.png)
It is also possible to check the content of the results.log file from the CLI:

`tng-cli -u http://pre-int-vnv-bcn.5gtango.eu result -g <Result_UUID>`

![imagen](https://user-images.githubusercontent.com/46524505/63421164-6c768580-c408-11e9-9c55-bd2bad627c33.png)

**Comment by DanielVilaFalcon** [comment]
I have included the comparison between the obtained result and the requirements.
![image](https://user-images.githubusercontent.com/46524505/66407362-5c812800-e9ed-11e9-9e90-db660ab39f68.png)

I have done it with the command "qperf". It is listening in the MS-VNF as a server and the client is running in the V&V probe The complete qperf's results are:
![image](https://user-images.githubusercontent.com/46524505/66455837-2a62db00-ea6c-11e9-8a56-6f9436e3b78c.png)
