### ISSUE TITLE
Create VnV-test-Com-F4 test (videoconference head-less WebRTC call)

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-communications-pilot#76]
This test checks if a videoconference can be estabished.
● It uses the Chrome head-less approach for the WebRTC call.

**Comment by DanielVilaFalcon** [comment]
It is done. Two containers are executed in the VnV test to implement a WebRTC call. We show the output of the command to prove that the WebRTC call was estabished:
`tcpdump -i lo udp -vv -X | grep "rooms.quobis.com"`
This command capture the UDP traffic and filter those who comes or goes to URL rooms.quobis.com. The output is similar to:
![Captura de pantalla de 2019-08-12 14-01-18](https://user-images.githubusercontent.com/46524505/62942306-4afa1600-bdd8-11e9-92b8-a12b4c21ebf2.png)
If the output is similar to the content shown in the picture, we can confirm that the call has been made successfully.

**Comment by DanielVilaFalcon** [comment]
Once we have fixed the problem with the VnV, we could do the pending tests.
This test try to prove that the WebRTC call from both head-less containers is established successfully, so we show as results the Puppeteer logs and the output of the tcpdump command mentioned in the previous comment.
The next pictures show the obtained results from the CLI and from the VnV platform.

![imagen](https://user-images.githubusercontent.com/46524505/63492844-8d97ae80-c4ba-11e9-90e0-237170e20023.png)

![imagen](https://user-images.githubusercontent.com/46524505/63492795-75c02a80-c4ba-11e9-9095-5a49da41b11a.png)
