### ISSUE TITLE
Implement Health status variable in both SNMP and Prometheu

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-communications-pilot#77]
Right now a fake implementation has been released. We need to enable it and work on the real implementation. It must monitor the status of all the VNFs and if any of them is not available provide the downtime in ms. If the value is '0' then everything is up un running.

**Comment by DanielVilaFalcon** [comment]
The health variable SNMP is working. A shell script runs ping commands to the VNF periodically to check if all the VNFs are avaliable. In the case of one of them would not be avaliable, the health SNMP variable is updated with the downtime in ms.
If all the VNF are working, the value of variable is 0.

It should be displayed in the monitoring Web Prometheus, but it doesnt work yet.
