### ISSUE TITLE
Health monitoring variable in Prometheus

### ISSUE THREAD

**Issue by DanielVilaFalcon** [sonata-nfv/tng-communications-pilot#84]
The health variable is implemented in a SNMP real version but it doesn't appear in the monitoring platform Prometheus. It should appear with the same value as the SNMP health vairable. @pkarkazis

**Comment by pkarkazis** [comment]
Hello @DanielVilaFalcon, did you add the SNMP information (oids etc) inside the vnfd?

**Comment by DanielVilaFalcon** [comment]
The problems with the SNMP variables are fixed. The "health" and "wacInstances" SNMP metrics appear in the Prometheus monitoring platform as it is shown in the following picture:

![image](https://user-images.githubusercontent.com/46524505/64096483-18519680-cd62-11e9-83fb-0185855caa20.png)
